### ISSUE TITLE
Question Regarding the Use of Position Encoding

### ISSUE THREAD

**Issue by breaddaerb** [kjslag/spacebyte#2]
https://github.com/kjslag/spacebyte/blob/321111315c92bce0bc2f9f1630cb0bc82b897c57/spacebyte.py#L66

Hi Kevin, thanks for the great work.
I notice that spacebyte both applies RoPE and trainable position encoding. And the paper also writes "...Although we apply RoPE embeddings, we also included trained position embeddings..."What is the rationale behind using both methods instead of choosing one? Are there specific scenarios or performance considerations that led to this decision?
Looking forward to your insights.

**Comment by kjslag** [comment]
I was using the position embedding before I added the RoPE code, and I forgot to consider turning off positional embeddings until after many of my experiments finished. I did not get around to checking the performance implication of turning off the positional embedding. I do not expect that it matters very much for model performance.

**Comment by breaddaerb** [comment]
Thanks!
